[package]
name = "rustweet"
version = "0.1.0"
authors = ["mayah"]
repository = "https://github.com/mayah/rustweet"

[dependencies]
oauth-client = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
